#通用环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/news_forum
    username: root
    password: 1286493714
  application:
    name: newsforum
  servlet:
    multipart:
      max-file-size: 10MB #单个文件最大值
      max-request-size: 10MB #总数据最大值
  data:
    redis:
      port: 6379
      host: localhost
  profiles:
    active: dev #环境切换

server:
  servlet:
    context-path: /start
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名与下划线命名的转换

---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
---
#测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8083